services:
  backend:
    build: .
    ports:
      - 8080:8080
    develop:
      watch:
        - action: sync+restart
          path: target/jdsa-0.0.1-SNAPSHOT.jar
          target: ./app/application.jar